# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# yamllint disable rule:comments
name: Commitlint
'on': [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable rule:line-length
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: wagoid/commitlint-github-action@9763196e10f27aef304c9b8b660d31d97fce0f99 # v5
