---
name: Test & release

'on':
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}',
                          github.event.repository.default_branch) }}

jobs:
  should-run:
    name: Prep / Should run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.action.outputs.should-run }}
    steps:
      - id: action
        # yamllint disable-line rule:line-length
        uses: techneg-it/should-workflow-run@dcbb88600d59ec2842778ef1e2d41f680f876329 # v1.0.0
  pre-commit:
    name: Lint / `pre-commit`
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    container: techneg/ci-pre-commit:v2.4.25@sha256:ff5192e893c1079fbf70e3ce6bfc3773815041786a75659793158be930ba7803
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
      - name: Export `CI_CACHE_ID` from container
        run: echo "CI_CACHE_ID=$(cat /.ci_cache_id)" >> $GITHUB_ENV
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: "${{ env.CI_CACHE_ID }}|\
                ${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: Run `pre-commit`
        run: |
          git config --global --add safe.directory $(pwd)
          pre-commit run --all-files --color always --verbose
          pre-commit run --color always --hook-stage manual commitlint-ci
  test:
    name: Test / Kitchen
    needs:
      - pre-commit
      - should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    container:
      image: techneg/ci-docker-python-ruby:v2.2.60@sha256:de98b8d1d3cf86639fe69bfc4f0416115d18300759c5ed2948ac56f973dd944f
      volumes:
        - .:/sockets
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        env:
          DOCKER_HOST: unix:///sockets/dind.sock
        options: --privileged
        volumes:
          - .:/sockets
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform: [debian-12-3006-12]
    steps:
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3.22
        with:
          detached: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # - uses: ruby/setup-ruby@2a18b06812b0e15bb916e1df298d3e740422c47e # v1.203.0
      #   with:
      #     bundler-cache: true
      #     ruby-version: 3.1
      - env:
          BUNDLE_DEPLOYMENT: true
          DOCKER_HOST: unix:///sockets/dind.sock
        run: |
          cat <<EOF > kitchen.local.yml
          driver:
            use_internal_docker_network: true
          EOF
          bundle version
          bundle config list
          bundle install --no-cache
          bin/kitchen test ${{ matrix.platform }}
  results:
    name: Release / Collect results
    permissions:
      checks: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # yamllint disable-line rule:line-length
      - uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          ignore: Release / Collect results
          ignore_pattern: ^GitLab CI
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "::notice ::Workflow success!"
